---
name: Auto commit
on:
  push:
    branches:
      - main
jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Sleep for seconds
        uses: jakejarvis/wait-action@master
        with:
          time: "1m"
          
      - name: Modify last update
        run: |+
          time=`date '+%Y-%m-%d %H:%M:%S'`
          cat > "README.md" <<EOF
          [![](https://img.shields.io/badge/profile-fiandev-blue)](https://github.com/fiandev)
          [![](https://komarev.com/ghpvc/?username=fiandev&label=Profile%20views&color=0a93d1&style=flat)](https://github.com/fiandev)
          
          ---
          ## ðŸ’« About Me:
          hi, i'm fian junior fullstack web developer from Indonesia ðŸ‡®ðŸ‡©
          
          ## quotes
          \`\`\`typescript
          import { Humanity } from "life";
          
          class Me extends Humanity {
            public static shortname: string = "fian"
            public age: number = 17
            public hobbies: string[] = ["code", "anime", "music", "learn new things"]
            
            public function about_me (): string {
              return "Hi, I'm fian, 
              I really like computer programming, 
              I know quite a lot of programming languages, 
              I am very happy if you invite me to join your project :)
              don't hesitate to contact me ðŸ˜Š"
            }
          }
          \`\`\`
          
          ## ðŸŒ Socials:
          [![Stack Overflow](https://img.shields.io/badge/-Stackoverflow-FE7A16?logo=stack-overflow&logoColor=white)](https://stackoverflow.com/users/fiandev)
          
          # ðŸ’» Tech Stack:
          <table border="1">
            <thead>
              <tr>
                <th>no</th>
                <th>environment</th>
                <th>stacks</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>1</td>
                <td>frontend</td>
                <td style="display: flex; gap: 2; align-items: center;">
                  <img style="width: 1rem; height: 1rem;" src="https://raw.githubusercontent.com/fiandev/static-assets/master/icons/bootstrap.svg" alt="bootstrap" />
                  <img style="width: 1rem; height: 1rem;" src="https://raw.githubusercontent.com/fiandev/static-assets/master/icons/reactjs.svg" alt="reactjs" />
                  <img style="width: 1rem; height: 1rem;" src="https://raw.githubusercontent.com/fiandev/static-assets/master/icons/tailwind.svg" alt="tailwind" />
                  <img style="width: 1rem; height: 1rem;" src="https://raw.githubusercontent.com/fiandev/static-assets/master/icons/sass.svg" alt="sass" />
                </td>
              </tr>
              <tr>
                <td>2</td>
                <td>backend</td>
                <td style="display: flex; gap: 2; align-items: center;">
                  <img style="width: 1rem; height: 1rem;" src="https://raw.githubusercontent.com/fiandev/static-assets/master/icons/php.svg" alt="php" />
                  <img style="width: 1rem; height: 1rem;" src="https://raw.githubusercontent.com/fiandev/static-assets/master/icons/laravel.svg" alt="laravel" />
                  <img style="width: 1rem; height: 1rem;" src="https://raw.githubusercontent.com/fiandev/static-assets/master/icons/javascript.svg" alt="javascript" />
                  <img style="width: 1rem; height: 1rem;" src="https://raw.githubusercontent.com/fiandev/static-assets/master/icons/python.svg" alt="python" />
                </td>
              </tr>
            </tbody>
          </table>
          
          # ðŸ“Š GitHub Stats:
          <img style="width: 20rem; height: auto;" src="https://github-readme-stats.vercel.app/api/top-langs/?username=fiandev&theme=react&hide_border=true&include_all_commits=false&count_private=false&layout=compact" alt="top languages" />
          <img style="width: 20rem; height: auto;" src="https://github-readme-stats.vercel.app/api?username=fiandev&theme=react&hide_border=true&include_all_commits=false&count_private=false" alt="top languages" />
          <img style="width: 20rem; height: auto;" src="https://github-readme-streak-stats.herokuapp.com/?user=fiandev&theme=react&hide_border=true" alt="top languages" />
          
          ---
          EOF

      - name: Commit changes
        run: |+
          git config --local user.email "wongkeras2@gmail.com"
          git config --local user.name "fiandev"
          git add -A

          time=`date '+%Y-%m-%d %H:%M:%S'`

          message="update: README.md | ${time}"

          git commit -m "${message}"

      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          directory: .
          branch: main
          github_token: ${{ secrets.TOKEN }}
